---
global-variables:
  aws-cli: &aws-cli docker.digital.homeoffice.gov.uk/dsa/cdl-terragrunt-docker:11
  vault-image: &vault-image quay.io/ukhomeofficedigital/hashicorp-vault:1.6.0
  terragrunt-image: &terragrunt-image quay.io/ukhomeofficedigital/dq-docker-terragrunt:v0.23.18

kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

x-anchors:
  retrieve-deployment-aws-key: &retrieve-deployment-aws-key
    # Retrive vault secrets
    - vault read aws_dacc_dq/creds/drone > aws_creds.json
    - export LEASE_ID=$(cat aws_creds.json | grep lease_id | awk -F ' ' '{print $2}')
    # Update the token TTL to 10mins
    - vault lease renew -increment=1200 $${LEASE_ID}
    # Get the AWS credentials
    - echo "export DEP_AWS_ACCESS_KEY_ID=$(cat aws_creds.json | grep access_key | awk -F ' ' '{print $2}')" > set_aws_secrets.sh
    - echo "export DEP_AWS_SECRET_ACCESS_KEY=$(cat aws_creds.json | grep secret_key | awk -F ' ' '{print $2}')" >> set_aws_secrets.sh
    - echo "export AWS_DEFAULT_REGION=eu-west-2" >> set_aws_secrets.sh
    # Since AWS is eventually consistent we need to sleep a little while so the AWS key is created and made available
    - sleep 15

  retrieve-state-aws-key: &retrieve-state-aws-key
    # Retrive vault secrets
    - vault read aws_dacc_dq/creds/drone > aws_creds.json
    - export LEASE_ID=$(cat aws_creds.json | grep lease_id | awk -F ' ' '{print $2}')
    # Update the token TTL to 10mins
    - vault lease renew -increment=1200 $${LEASE_ID}
    # Get the AWS credentials
    - echo "export STATE_AWS_ACCESS_KEY_ID=$(cat aws_creds.json | grep access_key | awk -F ' ' '{print $2}')" > state_secret.sh
    - echo "export STATE_AWS_SECRET_ACCESS_KEY=$(cat aws_creds.json | grep secret_key | awk -F ' ' '{print $2}')" >> state_secret.sh
    - echo "export AWS_DEFAULT_REGION=eu-west-2" >> state_secret.sh
    - sleep 15

tf-init: &tf-init
    - source state_secret.sh
    - source set_aws_secrets.sh
    # - export MOCK_ID=$${AWS_ACCESS_KEY_ID}
    # - export MOCK_KEY=$${AWS_SECRET_ACCESS_KEY}
    - export AWS_ACCESS_KEY_ID=$${STATE_AWS_ACCESS_KEY_ID}
    - export AWS_SECRET_ACCESS_KEY=$${STATE_AWS_SECRET_ACCESS_KEY}
    - export TF_VAR_ENV_ACCT_ID=$${DEP_AWS_ACCESS_KEY_ID}
    - export TF_VAR_ENV_ACCT_KEY=$${DEP_AWS_SECRET_ACCESS_KEY}
    - echo -e "provider \"aws\" {\n  region = \"eu-west-2\"\n}" > provider.tf
    - echo -e "terraform {\n  backend \"s3\" {}\n}" > backend.tf
    - echo -e "remote_state {\n  backend = \"s3\"\n  config = {\n  bucket = \"dacc-dq-test-coral-team\"\n  region = \"eu-west-2\"\n  dynamodb_table = \"terraform-state\"\n  key = \"$ENV/dq-tf-ais-marinetraffic.tfstate\"\n  encrypt = true \n  }\n}" > terragrunt.hcl
    - terragrunt init

  tf-validate: &tf-validate
    - source state_secret.sh
    - source set_aws_secrets.sh
    # - export MOCK_ID=$${AWS_ACCESS_KEY_ID}
    # - export MOCK_KEY=$${AWS_SECRET_ACCESS_KEY}
    - export AWS_ACCESS_KEY_ID=$${STATE_AWS_ACCESS_KEY_ID}
    - export AWS_SECRET_ACCESS_KEY=$${STATE_AWS_SECRET_ACCESS_KEY}
    - export TF_VAR_ENV_ACCT_ID=$${DEP_AWS_ACCESS_KEY_ID}
    - export TF_VAR_ENV_ACCT_KEY=$${DEP_AWS_SECRET_ACCESS_KEY}
    - terragrunt validate

  tf-plan: &tf-plan
    - source state_secret.sh
    - source set_aws_secrets.sh
    # - export MOCK_ID=$${AWS_ACCESS_KEY_ID}
    # - export MOCK_KEY=$${AWS_SECRET_ACCESS_KEY}
    - export AWS_ACCESS_KEY_ID=$${STATE_AWS_ACCESS_KEY_ID}
    - export AWS_SECRET_ACCESS_KEY=$${STATE_AWS_SECRET_ACCESS_KEY}
    - export TF_VAR_ENV_ACCT_ID=$${DEP_AWS_ACCESS_KEY_ID}
    - export TF_VAR_ENV_ACCT_KEY=$${DEP_AWS_SECRET_ACCESS_KEY}
    - terragrunt plan -lock=false -out=plan

  tf-apply: &tf-apply
    - source state_secret.sh
    - source set_aws_secrets.sh
    # - export MOCK_ID=$${AWS_ACCESS_KEY_ID}
    # - export MOCK_KEY=$${AWS_SECRET_ACCESS_KEY}
    - export AWS_ACCESS_KEY_ID=$${STATE_AWS_ACCESS_KEY_ID}
    - export AWS_SECRET_ACCESS_KEY=$${STATE_AWS_SECRET_ACCESS_KEY}
    - export TF_VAR_ENV_ACCT_ID=$${DEP_AWS_ACCESS_KEY_ID}
    - export TF_VAR_ENV_ACCT_KEY=$${DEP_AWS_SECRET_ACCESS_KEY}
    - terragrunt apply -auto-approve -parallelism=50 plan

steps:
- name: retrieve_aws_secrets_test
  pull: if-not-exists
  image: *vault-image
  commands:
    *retrieve-deployment-aws-key
  environment:
    VAULT_ADDR:
      from_secret: VAULT_ADDR_DEV
    VAULT_TOKEN:
      from_secret: VAULT_TOKEN_DEV
  when:
    event:
      - push
      - promote

- name: retrieve_aws_state_keys
  pull: if-not-exists
  image: *aws-cli
  commands:
    *retrieve-state-aws-key
  environment:
    VAULT_ADDR:
      from_secret: VAULT_ADDR_DEV
    VAULT_TOKEN:
      from_secret: VAULT_TOKEN_DEV
  when:
    event:
      - push
      - promote

- name: init-test
  pull: always
  image: *terragrunt-image
  commands:
    *tf-init
  environment:
    ENV: test
  when:
    branch:
      exclude:
      - main
    event:
    - push

- name: testsuite
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - docker run --rm -v $(pwd):/data -w /data hashicorp/terraform fmt --diff --check
  # environment:
  #   AWS_ACCESS_KEY_ID:
  #     from_secret: AWS_ACCESS_KEY_ID
  #   AWS_SECRET_ACCESS_KEY:
  #     from_secret: AWS_SECRET_ACCESS_KEY
  when:
    branch:
      exclude:
      - main
    event:
    - push

- name: validate-test
  pull: if-not-exists
  image: *terragrunt-image
  commands:
    *tf-validate
  when:
    branch:
      exclude:
      - main
    event:
    - push

- name: plan-test
  pull: if-not-exists
  image: *terragrunt-image
  commands:
    *tf-plan
  when:
    branch:
      exclude:
      - main
    event:
    - push

- name: apply-test
  pull: if-not-exists
  image: *terragrunt-image
  commands:
    *tf-apply
  when:
    branch:
      exclude:
      - main
      - plan/*
    event:
    - push

# - name: init-ci
#   pull: always
#   image: quay.io/ukhomeofficedigital/dq-docker-terragrunt:v0.23.18
#   commands:
#   - export MOCK_ID=$${AWS_ACCESS_KEY_ID}
#   - export MOCK_KEY=$${AWS_SECRET_ACCESS_KEY}
#   - export TF_VAR_ENV_ACCT_ID=$${AWS_ACCESS_KEY_ID}
#   - export TF_VAR_ENV_ACCT_KEY=$${AWS_SECRET_ACCESS_KEY}
#   - echo "provider \"aws\" { region = \"eu-west-2\" }" > provider.tf
#   - echo -e "terraform {\n  backend \"s3\" {}\n}" > backend.tf
#   - echo -e "remote_state {\n  backend = \"s3\"\n  config = {\n  bucket = \"dacc-dq-test-yellow-team\"\n  region = \"eu-west-2\"\n  dynamodb_table = \"terraform-state\"\n  key = \"ci/dq-tf-aws-compliance.tfstate\"\n  encrypt = true \n  }\n}" > terragrunt.hcl
#   - terragrunt init
#   environment:
#     AWS_ACCESS_KEY_ID:
#       from_secret: AWS_ACCESS_KEY_ID
#     AWS_SECRET_ACCESS_KEY:
#       from_secret: AWS_SECRET_ACCESS_KEY
#   when:
#     event:
#     - push

# - name: plan-ci
#   pull: always
#   image: quay.io/ukhomeofficedigital/dq-docker-terragrunt:v0.23.18
#   commands:
#   - export TF_VAR_ENV_ACCT_ID=$${CI_ACC_ID}
#   - export TF_VAR_ENV_ACCT_KEY=$${CI_ACC_KEY}
#   - terragrunt plan -lock=false -out=plan
#   environment:
#     AWS_ACCESS_KEY_ID:
#       from_secret: AWS_ACCESS_KEY_ID
#     AWS_SECRET_ACCESS_KEY:
#       from_secret: AWS_SECRET_ACCESS_KEY
#     CI_ACC_ID:
#       from_secret: CI_ACC_ID
#     CI_ACC_KEY:
#       from_secret: CI_ACC_KEY
#     TF_VAR_namespace: ci
#     TF_VAR_naming_suffix: apps-ci-dq
#   when:
#     branch:
#     - main
#     - plan/*
#     event:
#     - push

# - name: apply-ci
#   pull: always
#   image: quay.io/ukhomeofficedigital/dq-docker-terragrunt:v0.23.18
#   commands:
#   - export TF_VAR_ENV_ACCT_ID=$${CI_ACC_ID}
#   - export TF_VAR_ENV_ACCT_KEY=$${CI_ACC_KEY}
#   - terragrunt apply -auto-approve -parallelism=50 plan
#   environment:
#     AWS_ACCESS_KEY_ID:
#       from_secret: AWS_ACCESS_KEY_ID
#     AWS_SECRET_ACCESS_KEY:
#       from_secret: AWS_SECRET_ACCESS_KEY
#     CI_ACC_ID:
#       from_secret: CI_ACC_ID
#     CI_ACC_KEY:
#       from_secret: CI_ACC_KEY
#     TF_VAR_namespace: ci
#     TF_VAR_naming_suffix: apps-ci-dq
#   when:
#     branch:
#       include:
#       - main
#       exclude:
#       - plan/*
#     event:
#     - push

# - name: init-notprod
#   pull: always
#   image: quay.io/ukhomeofficedigital/dq-docker-terragrunt:v0.23.18
#   commands:
#   - export TF_VAR_ENV_ACCT_ID=$${NOTPROD_ACC_ID}
#   - export TF_VAR_ENV_ACCT_KEY=$${NOTPROD_ACC_KEY}
#   - echo -e "terraform {\n  backend \"s3\" {}\n}" > backend.tf
#   - echo -e "remote_state {\n  backend = \"s3\"\n  config = {\n  bucket = \"dacc-dq-test-yellow-team\"\n  region = \"eu-west-2\"\n  dynamodb_table = \"terraform-state\"\n  key = \"notprod/dq-tf-aws-compliance.tfstate\"\n  encrypt = true \n }\n}" > terragrunt.hcl
#   - terragrunt init
#   environment:
#     AWS_ACCESS_KEY_ID:
#       from_secret: AWS_ACCESS_KEY_ID
#     AWS_SECRET_ACCESS_KEY:
#       from_secret: AWS_SECRET_ACCESS_KEY
#     NOTPROD_ACC_ID:
#       from_secret: NOTPROD_ACC_ID
#     NOTPROD_ACC_KEY:
#       from_secret: NOTPROD_ACC_KEY
#     TF_VAR_namespace: notprod
#     TF_VAR_naming_suffix: apps-notprod-dq
#   when:
#     event:
#     - push

# - name: plan-notprod
#   pull: always
#   image: quay.io/ukhomeofficedigital/dq-docker-terragrunt:v0.23.18
#   commands:
#   - export TF_VAR_ENV_ACCT_ID=$${NOTPROD_ACC_ID}
#   - export TF_VAR_ENV_ACCT_KEY=$${NOTPROD_ACC_KEY}
#   - terragrunt plan -lock=false -out=plan
#   environment:
#     AWS_ACCESS_KEY_ID:
#       from_secret: AWS_ACCESS_KEY_ID
#     AWS_SECRET_ACCESS_KEY:
#       from_secret: AWS_SECRET_ACCESS_KEY
#     NOTPROD_ACC_ID:
#       from_secret: NOTPROD_ACC_ID
#     NOTPROD_ACC_KEY:
#       from_secret: NOTPROD_ACC_KEY
#     TF_VAR_namespace: notprod
#     TF_VAR_naming_suffix: apps-notprod-dq
#   when:
#     branch:
#     - main
#     - plan/*
#     event:
#     - push

# - name: apply-notprod
#   pull: always
#   image: quay.io/ukhomeofficedigital/dq-docker-terragrunt:v0.23.18
#   commands:
#   - export TF_VAR_ENV_ACCT_ID=$${NOTPROD_ACC_ID}
#   - export TF_VAR_ENV_ACCT_KEY=$${NOTPROD_ACC_KEY}
#   - terragrunt apply -auto-approve -parallelism=50 plan
#   environment:
#     AWS_ACCESS_KEY_ID:
#       from_secret: AWS_ACCESS_KEY_ID
#     AWS_SECRET_ACCESS_KEY:
#       from_secret: AWS_SECRET_ACCESS_KEY
#     NOTPROD_ACC_ID:
#       from_secret: NOTPROD_ACC_ID
#     NOTPROD_ACC_KEY:
#       from_secret: NOTPROD_ACC_KEY
#     TF_VAR_namespace: notprod
#     TF_VAR_naming_suffix: apps-notprod-dq
#   when:
#     branch:
#       include:
#       - main
#       exclude:
#       - plan/*
#     event:
#     - push

# - name: init-prod
#   pull: if-not-exists
#   image: quay.io/ukhomeofficedigital/dq-docker-terragrunt:v0.23.18
#   commands:
#   - export TF_VAR_ENV_ACCT_ID=$${PROD_ACC_ID}
#   - export TF_VAR_ENV_ACCT_KEY=$${PROD_ACC_KEY}
#   - echo -e "terraform {\n  backend \"s3\" {}\n}" > backend.tf
#   - echo -e "remote_state {\n  backend = \"s3\"\n  config = {\n  bucket = \"dacc-dq-test-yellow-team\"\n  region = \"eu-west-2\"\n  dynamodb_table = \"terraform-state\"\n  key = \"prod/dq-tf-aws-compliance.tfstate\"\n  encrypt = true \n }\n}" > terragrunt.hcl
#   - terragrunt init -reconfigure
#   environment:
#     AWS_ACCESS_KEY_ID:
#       from_secret: AWS_ACCESS_KEY_ID
#     AWS_SECRET_ACCESS_KEY:
#       from_secret: AWS_SECRET_ACCESS_KEY
#     PROD_ACC_ID:
#       from_secret: PROD_ACC_ID
#     PROD_ACC_KEY:
#       from_secret: PROD_ACC_KEY
#     TF_VAR_namespace: prod
#     TF_VAR_naming_suffix: apps-prod-dq
#   when:
#     event:
#     - promote
#     - push

# - name: plan-prod
#   pull: always
#   image: quay.io/ukhomeofficedigital/dq-docker-terragrunt:v0.23.18
#   commands:
#   - export TF_VAR_ENV_ACCT_ID=$${PROD_ACC_ID}
#   - export TF_VAR_ENV_ACCT_KEY=$${PROD_ACC_KEY}
#   - terragrunt plan -lock=false -out=prodplan
#   environment:
#     AWS_ACCESS_KEY_ID:
#       from_secret: AWS_ACCESS_KEY_ID
#     AWS_SECRET_ACCESS_KEY:
#       from_secret: AWS_SECRET_ACCESS_KEY
#     PROD_ACC_ID:
#       from_secret: PROD_ACC_ID
#     PROD_ACC_KEY:
#       from_secret: PROD_ACC_KEY
#     TF_VAR_namespace: prod
#     TF_VAR_naming_suffix: apps-prod-dq
#   when:
#     branch:
#     - main
#     - plan/*
#     event:
#     - promote
#     - push

# - name: apply-prod
#   pull: always
#   image: quay.io/ukhomeofficedigital/dq-docker-terragrunt:v0.23.18
#   commands:
#   - export TF_VAR_ENV_ACCT_ID=$${PROD_ACC_ID}
#   - export TF_VAR_ENV_ACCT_KEY=$${PROD_ACC_KEY}
#   - terragrunt apply -auto-approve -parallelism=50 prodplan
#   environment:
#     AWS_ACCESS_KEY_ID:
#       from_secret: AWS_ACCESS_KEY_ID
#     AWS_SECRET_ACCESS_KEY:
#       from_secret: AWS_SECRET_ACCESS_KEY
#     PROD_ACC_ID:
#       from_secret: PROD_ACC_ID
#     PROD_ACC_KEY:
#       from_secret: PROD_ACC_KEY
#     TF_VAR_namespace: prod
#     TF_VAR_naming_suffix: apps-prod-dq
#   when:
#     branch:
#     - main
#     event:
#     - promote
#     target:
#     - prod

- name: sonar-scanner
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/sonar-scanner:v3.0.3
  when:
    event:
    - push
    - pull_request
    target:
      exclude:
      - production

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
